### ISSUE TITLE
ToDo for first exposure

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [EAT-CODE-KITE-REPEAT/react-native-data-forms#1]
- [x] Add all types to the example with minimal props
- [x] Test all types on my app
- [x] Publish code communify
- [x] Create demo vid on iPhone
- [x] Create gif of that and add code + gif to docs
